# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
- stage: Scan
  displayName: Scan image
  jobs:
  - job: Scan
    displayName: Scan
    pool:
      vmImage: "ubuntu-latest"
    steps:
    - script: |
        apt update && apt install -y curl
        curl -sfL 'https://raw.githubusercontent.com/orcasecurity/orca-cli/main/install.sh' | bash #download installation script
        orca-cli -p "$default" secrets scan --path "${PWD}"  # Run Orca CLI scan against your code
      displayName: Orca Security Secrets Scan
      env:
        ORCA_SECURITY_API_TOKEN: aHR0cHM6Ly9hcHAudXMub3JjYXNlY3VyaXR5LmlvfHxHUFF4SXNaTERNN1NlNEw5N1lEZGJuVkN1TjZHajNZYg==
